name: "Client Build"
on:
  push:
    branches:
      - master
      - dev/*
      - devops
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build client Project
    runs-on: ubuntu-latest
    container: node:16-alpine3.13
    steps:
      - uses: actions/checkout@v2
      - name: Install all dependencies
      - run: npm i
      - name: Build client application
      - run: npm run build