name: "Server Deployment"
on:
  push:
    branches:
      - master
      - devops
jobs:
  deployment:
    name: Build server Project
    runs-on: ubuntu-latest
    container: node:16-alpine3.13
    steps:
      - uses: actions/checkout@v2
      - name: Install all dependencies
        run: npm i
        working-directory: server
      - name: Create env file
        run: |
          touch .env
          echo DB_HOST =${{ secrets.DB_HOST }} >> .env
          echo DB_USER =${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD =${{ secrets.DB_PASSWORD }} >> .env
          echo DB_PORT =${{ secrets.DB_PORT }} >> .env
          echo DB_DATABASE =${{ secrets.DB_DATABASE }} >> .env
        working-directory: server
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.DEP_HOST }}
          USERNAME: ${{ secrets.DEP_USERNAME }}
          PORT: ${{ secrets.DEP_PORT }}
          KEY: ${{ secrets.DEP_SSH }}
        with:
          source: "./server/, ./server/.env"
          target: "/lab/hawk"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEP_HOST }}
          USERNAME: ${{ secrets.DEP_USERNAME }}
          PORT: ${{ secrets.DEP_PORT }}
          KEY: ${{ secrets.DEP_SSH }}
          script: ls -l /lab/hawk/server